# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181025_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdate',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingdate',
            name='building',
        ),
        migrations.DeleteModel(
            name='BookingDate',
        ),
    ]
