# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181101_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Booking'),
        ),
    ]
