# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 12:48
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181101_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=b'C:/api/static/building_images'), upload_to=b''),
        ),
    ]
